name = "transformer-gamma3"
main = "worker.js"
compatibility_date = "2024-01-01"
minify = true

[build]
command = "bun run build"

# 静的アセットの設定
[assets]
directory = "dist"
include = ["**/*"]
exclude = []

[env.production]
name = "transformer-gamma3"
